arb-dir: lib/features/localization/l10n
template-arb-file: app_ru.arb
output-localization-file: app_localizations.dart
output-dir: lib/features/localization
synthetic-package: false
nullable-getter: false
