name: sql_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  auto_route: ^7.9.1
  flutter_riverpod: ^2.5.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  freezed_annotation: ^2.4.1
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.2.2
  collection: ^1.18.0
  share_plus: ^7.2.2
  path_provider: ^2.1.3
  gap: ^3.0.1
  json_annotation: ^4.8.1
  flutter_local_notifications: ^16.3.2
  notification_permissions: ^0.6.1
  flutter_svg: ^2.0.10+1
  custom_sliding_segmented_control: ^1.8.1
  pinput: ^4.0.0
  animated_toggle: ^0.1.3
  pdf: ^3.10.8
  permission_handler: ^11.3.1
  colorful_circular_progress_indicator: ^0.0.2
  package_info_plus: ^8.0.0
  flutter_launcher_icons: ^0.13.1
  sqflite: ^2.3.3+1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  auto_route_generator: ^7.3.2
  freezed: ^2.4.7
  json_serializable: 6.7.1
  flutter_gen_runner: ^5.4.0
  rename: ^3.0.2

flutter:
  uses-material-design: true
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/Manrope-ExtraLight.ttf
          weight: 200

  assets:
    - assets/icons/
    - assets/fonts/
    - assets/images/

flutter_gen:
  output: lib/src/assets/
  line_length: 100
  assets:
    enabled: true
    outputs:
      # Assets need to be referenced with the package option, see
      # https://docs.flutter.dev/development/ui/assets-and-images#from-packages
      class_name: SqlAppAssets

  # Optional
  integrations:
    flutter_svg: true

flutter_launcher_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
